import java.util.ArrayList;

public class Student {

    // my student class has an name, an ID, and an Arraylist of courses
    private String name;
    private long ID;
    private ArrayList<Courses> courses;

    // it has a default constructor and and an overloaded construtor, both generated by java/ide
    public Student() {
    }

    public Student(String name, long ID, ArrayList<Courses> courses) {
        this.name = name;
        this.ID = ID;
        this.courses = courses;
    }

    // it has getters and setters generated for me
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getID() {
        return ID;
    }

    public void setID(long ID) {
        this.ID = ID;
    }

    public ArrayList<Courses> getCourses() {
        return courses;
    }

    public void setCourses(ArrayList<Courses> courses) {
        this.courses = courses;
    }

    // it has a method that is used to display the text
    public String displayText(){
        //this is here to be sure that that thing output starts with an empty string
        String str = "";
        // this line says that the string equals the string + the name and then breaks to a new line using \n
        str += name + ":\n";
        // this enhanced for loop runs thorough our courses arraylist
        for (Courses c : courses) {
            // extra encapsulation! let the course tell you about itself! ;)
            // then the string equals the string + what the display text method finds in the array and then it returns the string
            str += c.displayText();
        }
        return str;
    }

}
